#!/usr/bin/env python3
"""Generates results/index.html: a static side-by-side comparison of the
frozen thesis tables (original_results/) and the reproduced tables from the
current run (results/<experiment>/reproduced_tables/).

No server and no external dependencies — open the file in a browser.
Images are referenced relative to the repository layout, so the report is
meant to be opened from results/ inside the cloned repository.
"""

import datetime
import html
import os

import pandas as pd

REPO_ROOT = os.environ.get("REPO_ROOT", "/workspace")
RESULTS_ROOT = os.path.join(REPO_ROOT, "results")
ORIGINAL_ROOT = os.path.join(REPO_ROOT, "original_results")

# (experiment dir, title, thesis reference, original dir override, filename filter)
# Table 6.14 sits with Market Basket N=100 in the thesis, but experiment E6
# (random_control) produces it — the last two entries split that folder.
EXPERIMENTS = [
    ("wetgrass_100", "E1: WetGrass, N = 100", "Thesis Section 6.7, Tables 6.3 and 6.4",
     None, None),
    ("wetgrass_10000", "E2: WetGrass, N = 10,000", "Thesis Section 6.7, Tables 6.5 and 6.6",
     None, None),
    # Table 6.7 (attribute encodings) describes the setup and is not
    # regenerated by runs, so it is left out of the pairing.
    ("nhanes", "E3: NHANES, N = 2,278", "Thesis Section 6.8, Tables 6.7 to 6.9",
     None, lambda f: "6_07" not in f),
    ("market_basket_100", "E4: Market Basket, N = 100",
     "Thesis Section 6.9, Tables 6.10 to 6.13 and Figure 6.1",
     None, lambda f: "6_14" not in f),
    ("market_basket_10000", "E5: Market Basket, N = 10,000",
     "Thesis Section 6.9, Tables 6.15 to 6.18",
     None, None),
    ("random_control", "E6: Random-structure robustness check",
     "Thesis Section 6.9, Table 6.14",
     "market_basket_100", lambda f: "6_14" in f),
]

CSS = """
body { font-family: -apple-system, "Segoe UI", Roboto, sans-serif; margin: 2rem auto;
       max-width: 1200px; padding: 0 1rem; color: #1c1e21; }
h1 { border-bottom: 3px solid #2980b9; padding-bottom: .3rem; }
h2 { margin-top: 2.5rem; border-bottom: 1px solid #ccc; padding-bottom: .2rem; }
h3 { margin-bottom: .3rem; }
.meta { color: #666; font-size: .9rem; }
.pair { display: flex; gap: 1.5rem; flex-wrap: wrap; margin-bottom: 1.5rem; }
.pane { flex: 1 1 420px; overflow-x: auto; }
.pane h4 { margin: .2rem 0 .4rem; font-size: .95rem; }
.pane.original h4 { color: #8e44ad; }
.pane.reproduced h4 { color: #27ae60; }
table { border-collapse: collapse; font-size: .85rem; width: 100%; }
th, td { border: 1px solid #ddd; padding: .3rem .5rem; text-align: right; }
th { background: #f5f6f7; }
td:first-child, th:first-child { text-align: left; }
img { max-width: 100%; border: 1px solid #ddd; margin: .5rem 0; }
img.fig-medium { max-width: 620px; display: block; }
.missing { color: #c0392b; font-style: italic; }
.note { background: #fdf6e3; border-left: 4px solid #f1c40f; padding: .6rem 1rem;
        margin: 1rem 0; font-size: .9rem; }
.note table { margin: .5rem 0; }
.note th, .note td { text-align: left; }
"""


# Thesis section and printed page for every result table shown in the report
TABLE_REFERENCES = {
    "6.3": ("Section 6.7", 55), "6.4": ("Section 6.7", 56),
    "6.5": ("Section 6.7", 59), "6.6": ("Section 6.7", 59),
    "6.8": ("Section 6.8", 62), "6.9": ("Section 6.8", 63),
    "6.10": ("Section 6.9", 66), "6.11": ("Section 6.9", 66),
    "6.12": ("Section 6.9", 68), "6.13": ("Section 6.9", 69),
    "6.14": ("Section 6.9", 70), "6.15": ("Section 6.9", 73),
    "6.16": ("Section 6.9", 73), "6.17": ("Section 6.9", 74),
    "6.18": ("Section 6.9", 75),
}


def table_html(csv_path):
    if not os.path.isfile(csv_path):
        return '<p class="missing">not available</p>'
    df = pd.read_csv(csv_path)
    return df.to_html(index=False, border=0, na_rep="")


def pair_html(title, number, original_csv, reproduced_csv):
    section, page = TABLE_REFERENCES.get(number, (None, None))
    ref = (f'<p class="meta">Thesis: Table {number}, {section}, page {page}.</p>'
           if section else "")

    # When a run executed only part of the configuration grid (QUICK mode),
    # variation tables come out shorter than the thesis tables or are not
    # generated at all; state this in the report instead of looking broken.
    note = ""
    if os.path.isfile(original_csv):
        orig_rows = len(pd.read_csv(original_csv))
        if not os.path.isfile(reproduced_csv):
            note = ('<p class="meta">Not generated by this run: none of the '
                    "configurations behind this table were executed. QUICK "
                    "mode runs only the headline configuration; a full run "
                    "generates this table completely.</p>")
        elif len(pd.read_csv(reproduced_csv)) < orig_rows:
            note = ('<p class="meta">This run executed only part of the '
                    "configuration grid, so rows appear for the executed "
                    "configurations only. A full run populates every "
                    "row.</p>")

    return f"""
<h3>{html.escape(title)}</h3>
{ref}
<div class="pair">
  <div class="pane original"><h4>Original (thesis)</h4>{table_html(original_csv)}</div>
  <div class="pane reproduced"><h4>Reproduced (this run)</h4>{table_html(reproduced_csv)}</div>
</div>
{note}"""


def pretty_table_name(fname):
    # table_6_03_cardinality_estimates.csv -> ("Table 6.3: cardinality estimates", "6.3")
    base = fname[:-4]
    parts = base.split("_")
    number = f"{parts[1]}.{parts[2].lstrip('0') or '0'}"
    rest = " ".join(parts[3:]).replace("qerror", "q-error")
    return f"Table {number}: {rest}", number


def experiment_section(exp, title, refs, orig_override, name_filter):
    orig_name = orig_override or exp
    orig_dir = os.path.join(ORIGINAL_ROOT, orig_name)
    repro_dir = os.path.join(RESULTS_ROOT, exp, "reproduced_tables")

    parts = [f"<h2>{html.escape(title)}</h2>",
             f'<p class="meta">{html.escape(refs)}</p>']

    if not os.path.isdir(orig_dir):
        parts.append('<p class="missing">no frozen reference for this experiment</p>')
        return "\n".join(parts)

    for fname in sorted(os.listdir(orig_dir)):
        if not fname.endswith(".csv"):
            continue
        if name_filter is not None and not name_filter(fname):
            continue
        title, number = pretty_table_name(fname)
        parts.append(pair_html(
            title, number,
            os.path.join(orig_dir, fname),
            os.path.join(repro_dir, fname),
        ))

    figure = os.path.join(RESULTS_ROOT, exp, "figure_6_1_sorted_qerror.png")
    if os.path.isfile(figure):
        parts.append(
            "<h3>Figure 6.1: sorted q-error profiles</h3>"
            '<p class="meta">Thesis: Figure 6.1, Section 6.9, page 67. '
            "Reproduced from this run's q-error data: per-query q-errors of "
            "the stable SA and SQA estimates and of the deterministic "
            "baselines, sorted per estimator.</p>"
            f'<img class="fig-medium" src="{exp}/figure_6_1_sorted_qerror.png" '
            'alt="Reproduced sorted q-error profiles">')

    combined = os.path.join(RESULTS_ROOT, exp, "combined_results.png")
    if os.path.isfile(combined):
        parts.append(
            "<h3>Comparison chart (headline configuration)</h3>"
            '<p class="meta">Generated by this run: per-query estimates of '
            "all estimators for the headline configuration.</p>"
            f'<img src="{exp}/combined_results.png" '
            'alt="Reproduced grouped bar chart">')

    return "\n".join(parts)


def main():
    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    sections = [experiment_section(*e) for e in EXPERIMENTS]

    body = f"""<meta charset="utf-8">
<title>AnnealBN-CE Reproduction Report</title>
<style>{CSS}</style>
<h1>AnnealBN-CE Reproduction Report</h1>
<p class="meta">Generated {stamp}. Frozen thesis values on the left,
values reproduced by this run on the right.</p>
<div class="note">
<p>Simulated annealing (SA) and simulated quantum annealing (SQA) are
stochastic solvers. Regenerated structures and estimates are therefore
expected to be similar, but not necessarily identical, to the values
reported in the thesis. A reproduction is considered successful when the
stable estimate vectors, the deterministic baseline columns, and the
qualitative orderings and trends agree with the thesis. The table below
states the expected level of agreement for each type of result table. The
mapping between reference files and thesis tables is documented in
original_results/MANIFEST.md.</p>
<table>
<tr><th>Table type</th><th>Thesis tables</th><th>Expected agreement</th></tr>
<tr><td>Cardinality estimates</td><td>6.3, 6.5, 6.8, 6.10, 6.15</td>
<td>The stable SA and SQA estimate vectors should match exactly or almost
exactly.</td></tr>
<tr><td>Chow–Liu and PostgreSQL columns</td><td>all</td>
<td>Deterministic values; these must match exactly, since the data and the
software versions are fixed.</td></tr>
<tr><td>Q-error summaries</td><td>6.4, 6.6, 6.9, 6.11, 6.16</td>
<td>Minimum, median, and maximum should agree closely, and the ordering
between the estimators must be preserved.</td></tr>
<tr><td>Read and trial variation</td><td>6.12, 6.13, 6.17, 6.18</td>
<td>Structure counts may differ between runs. The trend of fewer unique
structures and lower q-errors at larger read budgets must be
preserved.</td></tr>
<tr><td>Random-structure check</td><td>6.14</td>
<td>Values on the random side vary between runs. Annealing-learned
structures must show clearly lower median and maximum q-errors than random
structures.</td></tr>
</table>
</div>
{''.join(sections)}
"""

    out = os.path.join(RESULTS_ROOT, "index.html")
    os.makedirs(RESULTS_ROOT, exist_ok=True)
    with open(out, "w") as f:
        f.write(body)
    print(f"Report written to {out}")


if __name__ == "__main__":
    main()
